In [1]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd

In [2]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # learning rate
        self.epochs = epochs # iterations

    def _z_outcomes(self, inputs, weights):
        return np.dot(inputs, weights)

    def activation_function(self, z):
        return np.where(z>0, 1, 0)
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print("X with bias= ", X_with_bias)

        for epoch in range(self.epochs):
            print(f"---"*10)
            z = self._z_outcomes(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print("Predicted value after the forward pass: ", y_hat)
            
            self.error = self.y -y_hat
            print("Error at every step: \n", self.error)

            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print("Updated weights after epoch ", epoch, ": ",self.weights)

            print(f"---"*10)
            print("\n")

    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcomes(X_with_bias, self.weights)
        return self.activation_function(z)

In [3]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
y = np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [5]:
obj = Perceptron(eta=0.01, epochs=10) 

In [6]:
OR = {
    "x1": [0, 0, 1, 1],
    "x2": [0, 1, 0, 1],
    "y": [0, 1, 1, 1]
}
df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [7]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    return X, y

In [8]:
X, y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(ETA, EPOCHS)

model_or.fit(X, y)

X with bias=  [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
------------------------------
Predicted value after the forward pass:  [0 0 0 0]
Error at every step: 
 0    0
1    1
2    1
3    1
Name: y, dtype: int64
Updated weights after epoch  0 :  [ 0.19986249  0.19997518 -0.29996481]
------------------------------


------------------------------
Predicted value after the forward pass:  [1 1 1 1]
Error at every step: 
 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epoch  1 :  [ 0.19986249  0.19997518 -0.19996481]
------------------------------


------------------------------
Predicted value after the forward pass:  [1 1 1 1]
Error at every step: 
 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights after epoch  2 :  [ 0.19986249  0.19997518 -0.09996481]
------------------------------


------------------------------
Predicted value after the forward pass:  [1 1 1 1]
Error at every step: 
 0   -1
1    0
2    0
3    0
Name: y, dty

In [9]:

model_or.predict(X)

array([0, 1, 1, 1])